server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sgs?userSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: minseung
    password: min753951
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache: false
  redis:
    host: localhost
    port: 6379
    profiles:
      active: local
    expireTime:
      urlCash: 3600

